//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoWeb
    {
        public int Id { get; set; }
        public int IdCursoAlumno { get; set; }
        public int IdPlanPago { get; set; }
        public short NroCuota { get; set; }
        public System.DateTime FechaVto { get; set; }
        public decimal ImporteCuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal ImportePagado { get; set; }
        public decimal ImporteRecargo { get; set; }
        public decimal ImporteBeca { get; set; }
    
        public virtual CursoAlumnoWeb CursosAlumnosWeb { get; set; }
    }
}
