//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioEMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursos()
        {
            this.CursosAlumnos = new HashSet<CursosAlumnos>();
            this.PlanesPago = new HashSet<PlanesPago>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdCarrera { get; set; }
        public decimal ImporteCuota { get; set; }
        public decimal ImporteMatricula { get; set; }
        public Nullable<int> Modalidad { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursosAlumnos> CursosAlumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanesPago> PlanesPago { get; set; }
    }
}
