//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioEMail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMPorresEntities : DbContext
    {
        //public SMPorresEntities()
        //    : base("name=SMPorresEntities")
        //{
        //}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<BecasAlumnos> BecasAlumnos { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Cuotas> Cuotas { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<CursosAlumnos> CursosAlumnos { get; set; }
        public virtual DbSet<MediosPago> MediosPago { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<PlanesPago> PlanesPago { get; set; }
        public virtual DbSet<TiposDocumento> TiposDocumento { get; set; }
    }
}
