//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilidades.ConsultasWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultasWeb.SMPSoap")]
    public interface SMPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento alumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatos", ReplyAction="*")]
        Utilidades.ConsultasWeb.ActualizarDatosResponse ActualizarDatos(Utilidades.ConsultasWeb.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarDatosResponse> ActualizarDatosAsync(Utilidades.ConsultasWeb.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarConfiguracion", ReplyAction="*")]
        bool ActualizarConfiguracion(double interésPorMora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarConfiguracion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarConfiguracionAsync(double interésPorMora);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pwd del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPwd", ReplyAction="*")]
        Utilidades.ConsultasWeb.ActualizarPwdResponse ActualizarPwd(Utilidades.ConsultasWeb.ActualizarPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarPwdResponse> ActualizarPwdAsync(Utilidades.ConsultasWeb.ActualizarPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestAlive", ReplyAction="*")]
        bool TestAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> TestAliveAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatos", Namespace="http://tempuri.org/", Order=0)]
        public Utilidades.ConsultasWeb.ActualizarDatosRequestBody Body;
        
        public ActualizarDatosRequest() {
        }
        
        public ActualizarDatosRequest(Utilidades.ConsultasWeb.ActualizarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SMPorres.ConsultasWeb.Alumno alumno;
        
        public ActualizarDatosRequestBody() {
        }
        
        public ActualizarDatosRequestBody(SMPorres.ConsultasWeb.Alumno alumno) {
            this.alumno = alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Utilidades.ConsultasWeb.ActualizarDatosResponseBody Body;
        
        public ActualizarDatosResponse() {
        }
        
        public ActualizarDatosResponse(Utilidades.ConsultasWeb.ActualizarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarDatosResult;
        
        public ActualizarDatosResponseBody() {
        }
        
        public ActualizarDatosResponseBody(bool ActualizarDatosResult) {
            this.ActualizarDatosResult = ActualizarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPwd", Namespace="http://tempuri.org/", Order=0)]
        public Utilidades.ConsultasWeb.ActualizarPwdRequestBody Body;
        
        public ActualizarPwdRequest() {
        }
        
        public ActualizarPwdRequest(Utilidades.ConsultasWeb.ActualizarPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAlumno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public ActualizarPwdRequestBody() {
        }
        
        public ActualizarPwdRequestBody(int idAlumno, string pwd) {
            this.idAlumno = idAlumno;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Utilidades.ConsultasWeb.ActualizarPwdResponseBody Body;
        
        public ActualizarPwdResponse() {
        }
        
        public ActualizarPwdResponse(Utilidades.ConsultasWeb.ActualizarPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarPwdResult;
        
        public ActualizarPwdResponseBody() {
        }
        
        public ActualizarPwdResponseBody(bool ActualizarPwdResult) {
            this.ActualizarPwdResult = ActualizarPwdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMPSoapChannel : Utilidades.ConsultasWeb.SMPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMPSoapClient : System.ServiceModel.ClientBase<Utilidades.ConsultasWeb.SMPSoap>, Utilidades.ConsultasWeb.SMPSoap {
        
        public SMPSoapClient() {
        }
        
        public SMPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Utilidades.ConsultasWeb.ActualizarDatosResponse Utilidades.ConsultasWeb.SMPSoap.ActualizarDatos(Utilidades.ConsultasWeb.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatos(request);
        }
        
        public bool ActualizarDatos(SMPorres.ConsultasWeb.Alumno alumno) {
            Utilidades.ConsultasWeb.ActualizarDatosRequest inValue = new Utilidades.ConsultasWeb.ActualizarDatosRequest();
            inValue.Body = new Utilidades.ConsultasWeb.ActualizarDatosRequestBody();
            inValue.Body.alumno = alumno;
            Utilidades.ConsultasWeb.ActualizarDatosResponse retVal = ((Utilidades.ConsultasWeb.SMPSoap)(this)).ActualizarDatos(inValue);
            return retVal.Body.ActualizarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarDatosResponse> Utilidades.ConsultasWeb.SMPSoap.ActualizarDatosAsync(Utilidades.ConsultasWeb.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarDatosResponse> ActualizarDatosAsync(SMPorres.ConsultasWeb.Alumno alumno) {
            Utilidades.ConsultasWeb.ActualizarDatosRequest inValue = new Utilidades.ConsultasWeb.ActualizarDatosRequest();
            inValue.Body = new Utilidades.ConsultasWeb.ActualizarDatosRequestBody();
            inValue.Body.alumno = alumno;
            return ((Utilidades.ConsultasWeb.SMPSoap)(this)).ActualizarDatosAsync(inValue);
        }
        
        public bool ActualizarConfiguracion(double interésPorMora) {
            return base.Channel.ActualizarConfiguracion(interésPorMora);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarConfiguracionAsync(double interésPorMora) {
            return base.Channel.ActualizarConfiguracionAsync(interésPorMora);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Utilidades.ConsultasWeb.ActualizarPwdResponse Utilidades.ConsultasWeb.SMPSoap.ActualizarPwd(Utilidades.ConsultasWeb.ActualizarPwdRequest request) {
            return base.Channel.ActualizarPwd(request);
        }
        
        public bool ActualizarPwd(int idAlumno, string pwd) {
            Utilidades.ConsultasWeb.ActualizarPwdRequest inValue = new Utilidades.ConsultasWeb.ActualizarPwdRequest();
            inValue.Body = new Utilidades.ConsultasWeb.ActualizarPwdRequestBody();
            inValue.Body.idAlumno = idAlumno;
            inValue.Body.pwd = pwd;
            Utilidades.ConsultasWeb.ActualizarPwdResponse retVal = ((Utilidades.ConsultasWeb.SMPSoap)(this)).ActualizarPwd(inValue);
            return retVal.Body.ActualizarPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarPwdResponse> Utilidades.ConsultasWeb.SMPSoap.ActualizarPwdAsync(Utilidades.ConsultasWeb.ActualizarPwdRequest request) {
            return base.Channel.ActualizarPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Utilidades.ConsultasWeb.ActualizarPwdResponse> ActualizarPwdAsync(int idAlumno, string pwd) {
            Utilidades.ConsultasWeb.ActualizarPwdRequest inValue = new Utilidades.ConsultasWeb.ActualizarPwdRequest();
            inValue.Body = new Utilidades.ConsultasWeb.ActualizarPwdRequestBody();
            inValue.Body.idAlumno = idAlumno;
            inValue.Body.pwd = pwd;
            return ((Utilidades.ConsultasWeb.SMPSoap)(this)).ActualizarPwdAsync(inValue);
        }
        
        public bool TestAlive() {
            return base.Channel.TestAlive();
        }
        
        public System.Threading.Tasks.Task<bool> TestAliveAsync() {
            return base.Channel.TestAliveAsync();
        }
    }
}
