//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPorres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int IdTipoDocumento { get; set; }
        public decimal NroDocumento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string EMail { get; set; }
        public string Direccion { get; set; }
        public int IdDomicilio { get; set; }
        public byte Estado { get; set; }
    
        public virtual Domicilio Domicilio { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
