//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPorres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BecaAlumno
    {
        public int Id { get; set; }
        public int IdPago { get; set; }
        public int IdAlumno { get; set; }
        public double PorcBeca { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
