//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPorres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        public int Id { get; set; }
        public short NroCuota { get; set; }
        public System.DateTime VtoBonificacion { get; set; }
        public System.DateTime VtoCuota { get; set; }
    }
}
