//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPorres.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pago()
        {
            this.PagosAsientos = new HashSet<Pago>();
        }
    
        public int IdPago { get; set; }
        public int IdPlanPago { get; set; }
        public System.DateTime Fecha { get; set; }
        public short NroCuota { get; set; }
        public decimal ImportePagado { get; set; }
        public decimal ImporteCuota { get; set; }
        public short PorcDescPagoTermino { get; set; }
        public decimal ImportePagoTermino { get; set; }
        public short PorcentajeBeca { get; set; }
        public Nullable<int> IdBecaAlumno { get; set; }
        public decimal Recargo { get; set; }
        public int IdMedioPago { get; set; }
        public Nullable<int> IdArchivo { get; set; }
        public short EsContrasiento { get; set; }
        public Nullable<int> IdPagoAsiento { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaGrabacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> PagosAsientos { get; set; }
        public virtual Pago PagoAsiento { get; set; }
        public virtual PlanesPago PlanesPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
