//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesDeuda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosAlumno
    {
        public int Id { get; set; }
        public int IdCurso { get; set; }
        public int IdAlumno { get; set; }
        public short CicloLectivo { get; set; }
    
        public virtual Alumno Alumnos { get; set; }
        public virtual Curso Cursos { get; set; }
    }
}
