//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMPorres.ConsultasWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        private decimal NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMPorres.ConsultasWeb.CursoAlumno[] CursosAlumnosField;
        
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((this.NroDocumentoField.Equals(value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SMPorres.ConsultasWeb.CursoAlumno[] CursosAlumnos {
            get {
                return this.CursosAlumnosField;
            }
            set {
                if ((object.ReferenceEquals(this.CursosAlumnosField, value) != true)) {
                    this.CursosAlumnosField = value;
                    this.RaisePropertyChanged("CursosAlumnos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoAlumno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CursoAlumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int IdCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        private int IdCarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMPorres.ConsultasWeb.Pago[] PagosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCurso {
            get {
                return this.IdCursoField;
            }
            set {
                if ((this.IdCursoField.Equals(value) != true)) {
                    this.IdCursoField = value;
                    this.RaisePropertyChanged("IdCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdCarrera {
            get {
                return this.IdCarreraField;
            }
            set {
                if ((this.IdCarreraField.Equals(value) != true)) {
                    this.IdCarreraField = value;
                    this.RaisePropertyChanged("IdCarrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public SMPorres.ConsultasWeb.Pago[] Pagos {
            get {
                return this.PagosField;
            }
            set {
                if ((object.ReferenceEquals(this.PagosField, value) != true)) {
                    this.PagosField = value;
                    this.RaisePropertyChanged("Pagos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int IdPlanPagoField;
        
        private int NroCuotaField;
        
        private System.DateTime FechaVtoField;
        
        private System.Nullable<System.DateTime> FechaField;
        
        private decimal ImporteCuotaField;
        
        private System.Nullable<decimal> ImportePagadoField;
        
        private System.Nullable<decimal> ImporteRecargoField;
        
        private System.Nullable<decimal> ImporteBecaField;
        
        private System.Nullable<decimal> ImportePagoTérminoField;
        
        private System.Nullable<short> PorcentajeBecaField;
        
        private System.DateTime FechaVtoPagoTérminoField;
        
        private System.Nullable<byte> TipoBecaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPlanPago {
            get {
                return this.IdPlanPagoField;
            }
            set {
                if ((this.IdPlanPagoField.Equals(value) != true)) {
                    this.IdPlanPagoField = value;
                    this.RaisePropertyChanged("IdPlanPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NroCuota {
            get {
                return this.NroCuotaField;
            }
            set {
                if ((this.NroCuotaField.Equals(value) != true)) {
                    this.NroCuotaField = value;
                    this.RaisePropertyChanged("NroCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaVto {
            get {
                return this.FechaVtoField;
            }
            set {
                if ((this.FechaVtoField.Equals(value) != true)) {
                    this.FechaVtoField = value;
                    this.RaisePropertyChanged("FechaVto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal ImporteCuota {
            get {
                return this.ImporteCuotaField;
            }
            set {
                if ((this.ImporteCuotaField.Equals(value) != true)) {
                    this.ImporteCuotaField = value;
                    this.RaisePropertyChanged("ImporteCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> ImportePagado {
            get {
                return this.ImportePagadoField;
            }
            set {
                if ((this.ImportePagadoField.Equals(value) != true)) {
                    this.ImportePagadoField = value;
                    this.RaisePropertyChanged("ImportePagado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> ImporteRecargo {
            get {
                return this.ImporteRecargoField;
            }
            set {
                if ((this.ImporteRecargoField.Equals(value) != true)) {
                    this.ImporteRecargoField = value;
                    this.RaisePropertyChanged("ImporteRecargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> ImporteBeca {
            get {
                return this.ImporteBecaField;
            }
            set {
                if ((this.ImporteBecaField.Equals(value) != true)) {
                    this.ImporteBecaField = value;
                    this.RaisePropertyChanged("ImporteBeca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> ImportePagoTérmino {
            get {
                return this.ImportePagoTérminoField;
            }
            set {
                if ((this.ImportePagoTérminoField.Equals(value) != true)) {
                    this.ImportePagoTérminoField = value;
                    this.RaisePropertyChanged("ImportePagoTérmino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<short> PorcentajeBeca {
            get {
                return this.PorcentajeBecaField;
            }
            set {
                if ((this.PorcentajeBecaField.Equals(value) != true)) {
                    this.PorcentajeBecaField = value;
                    this.RaisePropertyChanged("PorcentajeBeca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaVtoPagoTérmino {
            get {
                return this.FechaVtoPagoTérminoField;
            }
            set {
                if ((this.FechaVtoPagoTérminoField.Equals(value) != true)) {
                    this.FechaVtoPagoTérminoField = value;
                    this.RaisePropertyChanged("FechaVtoPagoTérmino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<byte> TipoBeca {
            get {
                return this.TipoBecaField;
            }
            set {
                if ((this.TipoBecaField.Equals(value) != true)) {
                    this.TipoBecaField = value;
                    this.RaisePropertyChanged("TipoBeca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultasWeb.SMPSoap")]
    public interface SMPSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento alumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatos", ReplyAction="*")]
        SMPorres.ConsultasWeb.ActualizarDatosResponse ActualizarDatos(SMPorres.ConsultasWeb.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarDatosResponse> ActualizarDatosAsync(SMPorres.ConsultasWeb.ActualizarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarConfiguracion", ReplyAction="*")]
        bool ActualizarConfiguracion(double interésPorMora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarConfiguracion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarConfiguracionAsync(double interésPorMora);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pwd del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPwd", ReplyAction="*")]
        SMPorres.ConsultasWeb.ActualizarPwdResponse ActualizarPwd(SMPorres.ConsultasWeb.ActualizarPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarPwdResponse> ActualizarPwdAsync(SMPorres.ConsultasWeb.ActualizarPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestAlive", ReplyAction="*")]
        bool TestAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> TestAliveAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatos", Namespace="http://tempuri.org/", Order=0)]
        public SMPorres.ConsultasWeb.ActualizarDatosRequestBody Body;
        
        public ActualizarDatosRequest() {
        }
        
        public ActualizarDatosRequest(SMPorres.ConsultasWeb.ActualizarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SMPorres.ConsultasWeb.Alumno alumno;
        
        public ActualizarDatosRequestBody() {
        }
        
        public ActualizarDatosRequestBody(SMPorres.ConsultasWeb.Alumno alumno) {
            this.alumno = alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMPorres.ConsultasWeb.ActualizarDatosResponseBody Body;
        
        public ActualizarDatosResponse() {
        }
        
        public ActualizarDatosResponse(SMPorres.ConsultasWeb.ActualizarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarDatosResult;
        
        public ActualizarDatosResponseBody() {
        }
        
        public ActualizarDatosResponseBody(bool ActualizarDatosResult) {
            this.ActualizarDatosResult = ActualizarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPwd", Namespace="http://tempuri.org/", Order=0)]
        public SMPorres.ConsultasWeb.ActualizarPwdRequestBody Body;
        
        public ActualizarPwdRequest() {
        }
        
        public ActualizarPwdRequest(SMPorres.ConsultasWeb.ActualizarPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAlumno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public ActualizarPwdRequestBody() {
        }
        
        public ActualizarPwdRequestBody(int idAlumno, string pwd) {
            this.idAlumno = idAlumno;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMPorres.ConsultasWeb.ActualizarPwdResponseBody Body;
        
        public ActualizarPwdResponse() {
        }
        
        public ActualizarPwdResponse(SMPorres.ConsultasWeb.ActualizarPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarPwdResult;
        
        public ActualizarPwdResponseBody() {
        }
        
        public ActualizarPwdResponseBody(bool ActualizarPwdResult) {
            this.ActualizarPwdResult = ActualizarPwdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMPSoapChannel : SMPorres.ConsultasWeb.SMPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMPSoapClient : System.ServiceModel.ClientBase<SMPorres.ConsultasWeb.SMPSoap>, SMPorres.ConsultasWeb.SMPSoap {
        
        public SMPSoapClient() {
        }
        
        public SMPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMPorres.ConsultasWeb.ActualizarDatosResponse SMPorres.ConsultasWeb.SMPSoap.ActualizarDatos(SMPorres.ConsultasWeb.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatos(request);
        }
        
        public bool ActualizarDatos(SMPorres.ConsultasWeb.Alumno alumno) {
            SMPorres.ConsultasWeb.ActualizarDatosRequest inValue = new SMPorres.ConsultasWeb.ActualizarDatosRequest();
            inValue.Body = new SMPorres.ConsultasWeb.ActualizarDatosRequestBody();
            inValue.Body.alumno = alumno;
            SMPorres.ConsultasWeb.ActualizarDatosResponse retVal = ((SMPorres.ConsultasWeb.SMPSoap)(this)).ActualizarDatos(inValue);
            return retVal.Body.ActualizarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarDatosResponse> SMPorres.ConsultasWeb.SMPSoap.ActualizarDatosAsync(SMPorres.ConsultasWeb.ActualizarDatosRequest request) {
            return base.Channel.ActualizarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarDatosResponse> ActualizarDatosAsync(SMPorres.ConsultasWeb.Alumno alumno) {
            SMPorres.ConsultasWeb.ActualizarDatosRequest inValue = new SMPorres.ConsultasWeb.ActualizarDatosRequest();
            inValue.Body = new SMPorres.ConsultasWeb.ActualizarDatosRequestBody();
            inValue.Body.alumno = alumno;
            return ((SMPorres.ConsultasWeb.SMPSoap)(this)).ActualizarDatosAsync(inValue);
        }
        
        public bool ActualizarConfiguracion(double interésPorMora) {
            return base.Channel.ActualizarConfiguracion(interésPorMora);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarConfiguracionAsync(double interésPorMora) {
            return base.Channel.ActualizarConfiguracionAsync(interésPorMora);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMPorres.ConsultasWeb.ActualizarPwdResponse SMPorres.ConsultasWeb.SMPSoap.ActualizarPwd(SMPorres.ConsultasWeb.ActualizarPwdRequest request) {
            return base.Channel.ActualizarPwd(request);
        }
        
        public bool ActualizarPwd(int idAlumno, string pwd) {
            SMPorres.ConsultasWeb.ActualizarPwdRequest inValue = new SMPorres.ConsultasWeb.ActualizarPwdRequest();
            inValue.Body = new SMPorres.ConsultasWeb.ActualizarPwdRequestBody();
            inValue.Body.idAlumno = idAlumno;
            inValue.Body.pwd = pwd;
            SMPorres.ConsultasWeb.ActualizarPwdResponse retVal = ((SMPorres.ConsultasWeb.SMPSoap)(this)).ActualizarPwd(inValue);
            return retVal.Body.ActualizarPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarPwdResponse> SMPorres.ConsultasWeb.SMPSoap.ActualizarPwdAsync(SMPorres.ConsultasWeb.ActualizarPwdRequest request) {
            return base.Channel.ActualizarPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMPorres.ConsultasWeb.ActualizarPwdResponse> ActualizarPwdAsync(int idAlumno, string pwd) {
            SMPorres.ConsultasWeb.ActualizarPwdRequest inValue = new SMPorres.ConsultasWeb.ActualizarPwdRequest();
            inValue.Body = new SMPorres.ConsultasWeb.ActualizarPwdRequestBody();
            inValue.Body.idAlumno = idAlumno;
            inValue.Body.pwd = pwd;
            return ((SMPorres.ConsultasWeb.SMPSoap)(this)).ActualizarPwdAsync(inValue);
        }
        
        public bool TestAlive() {
            return base.Channel.TestAlive();
        }
        
        public System.Threading.Tasks.Task<bool> TestAliveAsync() {
            return base.Channel.TestAliveAsync();
        }
    }
}
