insert into departamentos(id, idprovincia, nombre) values(1, 1, 'Aguirre')
insert into departamentos(id, idprovincia, nombre) values(2, 1, 'Alberdi')
insert into departamentos(id, idprovincia, nombre) values(3, 1, 'Atamisqui')
insert into departamentos(id, idprovincia, nombre) values(4, 1, 'Avellaneda')
insert into departamentos(id, idprovincia, nombre) values(5, 1, 'Banda')
insert into departamentos(id, idprovincia, nombre) values(6, 1, 'Belgrano')
insert into departamentos(id, idprovincia, nombre) values(7, 1, 'Capital')
insert into departamentos(id, idprovincia, nombre) values(8, 1, 'Choya')
insert into departamentos(id, idprovincia, nombre) values(9, 1, 'Copo')
insert into departamentos(id, idprovincia, nombre) values(10, 1, 'Figueroa')
insert into departamentos(id, idprovincia, nombre) values(11, 1, 'Guasayan')
insert into departamentos(id, idprovincia, nombre) values(12, 1, 'Jimenez')
insert into departamentos(id, idprovincia, nombre) values(13, 1, 'Juan F.Ibarra')
insert into departamentos(id, idprovincia, nombre) values(14, 1, 'Loreto')
insert into departamentos(id, idprovincia, nombre) values(15, 1, 'Moreno')
insert into departamentos(id, idprovincia, nombre) values(16, 1, 'Ojo De Agua')
insert into departamentos(id, idprovincia, nombre) values(17, 1, 'Pellegrini')
insert into departamentos(id, idprovincia, nombre) values(18, 1, 'Quebrachos')
insert into departamentos(id, idprovincia, nombre) values(19, 1, 'Rio Hondo')
insert into departamentos(id, idprovincia, nombre) values(20, 1, 'Rivadavia')
insert into departamentos(id, idprovincia, nombre) values(21, 1, 'Robles')
insert into departamentos(id, idprovincia, nombre) values(22, 1, 'San Martin')
insert into departamentos(id, idprovincia, nombre) values(23, 1, 'Sarmiento')
insert into departamentos(id, idprovincia, nombre) values(24, 1, 'Silipica')
insert into departamentos(id, idprovincia, nombre) values(25, 1, 'Taboada')
insert into departamentos(id, idprovincia, nombre) values(26, 1, 'Salavina')
insert into departamentos(id, idprovincia, nombre) values(27, 1, 'Mitre')
